apiVersion: v1
appVersion: 0.7.1
description: Report Kubernetes cluster and pod resource requests vs usage and generate static HTML
name: kube-resource-report
version: 0.10.1
home: https://codeberg.org/hjacobs/kube-resource-report
