apiVersion: v1
appVersion: "22.8.0"
description: Report Kubernetes cluster and pod resource requests vs usage and generate static HTML
name: kube-resource-report
version: 0.7.8
home: https://codeberg.org/hjacobs/kube-resource-report
